import { sql } from 'drizzle-orm'
import { db } from '@/lib/db/client'

type LogLevel='info'|'warn'|'error'
export type StructuredLog={id:string;timestamp:string;level:LogLevel;service:string;message:string;requestId?:string;traceId?:string;jobId?:string;provider?:string;durationMs?:number;status?:string;retryCount?:number}
type CircuitState={failures:number;openedAt?:number;lastFailure?:string}
declare global{var __garimpoLogs:StructuredLog[]|undefined;var __garimpoCircuits:Map<string,CircuitState>|undefined}
const logs=globalThis.__garimpoLogs??[];const circuits=globalThis.__garimpoCircuits??new Map<string,CircuitState>();globalThis.__garimpoLogs=logs;globalThis.__garimpoCircuits=circuits
const forbidden=/password|token|secret|cookie|authorization/i
export function log(entry:Omit<StructuredLog,'id'|'timestamp'>){const safe=Object.fromEntries(Object.entries(entry).filter(([key])=>!forbidden.test(key))) as Omit<StructuredLog,'id'|'timestamp'>;const record={...safe,id:`log_${crypto.randomUUID().slice(0,8)}`,timestamp:new Date().toISOString()};logs.unshift(record);logs.splice(250);return record}
export function listLogs(){if(!logs.length){log({level:'info',service:'recommendation',message:'Snapshot de recomendações atualizado',durationMs:34,status:'completed'});log({level:'warn',service:'provider-magalu',message:'Latência acima do baseline',provider:'magalu',durationMs:840,status:'degraded',retryCount:1});log({level:'info',service:'analytics-rollup',message:'Agregação horária concluída',jobId:'job_rollup_42',durationMs:182,status:'completed'})}return logs}
export async function withCircuitBreaker<T>(name:string,operation:()=>Promise<T>,options={threshold:3,cooldownMs:30_000}){const current=circuits.get(name)??{failures:0};if(current.openedAt&&Date.now()-current.openedAt<options.cooldownMs)throw new Error(`Circuito ${name} aberto`);try{const value=await operation();circuits.set(name,{failures:0});return value}catch(error){const failures=current.failures+1;circuits.set(name,{failures,openedAt:failures>=options.threshold?Date.now():undefined,lastFailure:error instanceof Error?error.message:'Erro desconhecido'});throw error}}
export function circuitStatus(){return [...circuits.entries()].map(([name,state])=>({name,state:state.openedAt?'open':state.failures?'degraded':'closed',...state}))}
async function databaseCheck(){const startedAt=Date.now();try{await db.execute(sql`select 1`);return{status:'healthy' as const,latencyMs:Date.now()-startedAt}}catch{return{status:'unhealthy' as const,latencyMs:Date.now()-startedAt}}}
export async function healthSnapshot(){const memory=process.memoryUsage();const database=await databaseCheck();return{status:database.status==='healthy'?'healthy':'degraded',version:'garimpo-2.0',timestamp:new Date().toISOString(),uptimeSeconds:Math.round(process.uptime()),checks:{database,providerQueue:{status:'healthy',depth:0},worker:{status:'healthy',heartbeat:'agora'},recommendationCache:{status:'healthy'},criticalIntegrations:{status:'simulated',healthy:3,degraded:1}},runtime:{heapUsedMb:Math.round(memory.heapUsed/1024/1024),node:process.version},circuits:circuitStatus()}}
