import { expect, test } from '@playwright/test'

test('destaques alternam, pausam e respeitam movimento reduzido', async ({ page }) => {
  await page.route('**/api/auth/get-session**', route => route.fulfill({ json: null }))
  await page.addInitScript(() => localStorage.setItem('garimpo:consent', 'false'))
  await page.emulateMedia({ reducedMotion: 'no-preference' })
  await page.clock.install()
  await page.goto('/')
  const carousel = page.getByRole('region', { name: 'Produtos em destaque' })
  await expect(carousel.getByRole('button', { name: 'Pausar destaques' })).toBeVisible()
  const firstName = await carousel.locator('h2').textContent()
  await page.clock.runFor(6600)
  await expect(carousel.locator('h2')).not.toHaveText(firstName!)
  await carousel.getByRole('button', { name: 'Pausar destaques' }).click()
  await expect(carousel.getByRole('button', { name: 'Reproduzir destaques' })).toBeVisible()
  const pausedName = await carousel.locator('h2').textContent()
  await page.mouse.move(0, 0)
  await page.clock.runFor(14000)
  await expect(carousel.locator('h2')).toHaveText(pausedName!)
  await carousel.getByRole('button', { name: 'Próximo destaque' }).click()
  await expect(carousel.locator('h2')).not.toHaveText(pausedName!)
  await carousel.getByRole('button', { name: /Mostrar destaque 1:/ }).click()
  await expect(carousel.locator('h2')).toHaveText(firstName!)
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.reload()
  await expect(carousel.getByRole('button', { name: 'Reproduzir destaques' })).toBeVisible()
  const reducedName = await carousel.locator('h2').textContent()
  await page.clock.runFor(14000)
  await expect(carousel.locator('h2')).toHaveText(reducedName!)
  await expect(carousel.getByRole('link', { name: 'Comprar agora', exact: true })).toHaveAttribute('href', /^https:\/\//)
  await expect(carousel.getByText('Ver detalhes do produto', { exact: true })).toHaveCount(0)
  await carousel.getByRole('link', { name: /^Ver detalhes de / }).click()
  await expect(page).toHaveURL(/\/produto\//)
  await expect(page.getByRole('heading', { name: reducedName!, exact: true }).first()).toBeVisible()
})
