import { expect,test } from '@playwright/test'
test('home abre detalhes pelo card e compra direta pelo botão', async ({ page, context }) => {
  await page.addInitScript(() => localStorage.setItem('garimpo:consent', 'false'))
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Achados para conhecer.' })).toBeVisible()
  await expect(page.locator('section[aria-labelledby="home-categories-title"] a').first()).toBeVisible()
  const card = page.locator('.product-card').first()
  const productName = await card.locator('h3').innerText()
  await expect(card.locator('.product-buy-button')).toHaveAttribute('href', /^https:\/\//)
  await expect(card.locator('.product-buy-button')).toHaveAttribute('target', '_blank')
  const offerUrl = await card.locator('.product-buy-button').getAttribute('href')
  await expect(card.locator('.product-buy-button')).toHaveText('Comprar agora')
  await expect(card.locator('.product-sold-count')).toHaveText(/vendidos?$/)
  await expect(card.locator('.product-card-link')).toHaveAttribute('href', /^\/produto\//)
  await expect(card.getByText('Ver detalhes', { exact: true })).toHaveCount(0)
  await context.route(offerUrl!, route => route.fulfill({ body: 'Oferta da loja' }))
  const buyPopupPromise = page.waitForEvent('popup')
  await card.locator('.product-buy-button').click()
  const buyPopup = await buyPopupPromise
  await expect(buyPopup).toHaveURL(offerUrl!)
  await buyPopup.close()
  await expect(page).toHaveURL(/:\d+\/$/)
  await card.getByRole('button', { name: /aos favoritos/ }).click()
  await expect(card.getByRole('button', { name: /dos favoritos/ })).toHaveAttribute('aria-pressed', 'true')
  await card.getByRole('button', { name: /ao comparador/ }).click()
  await expect(card.getByRole('button', { name: /do comparador/ })).toHaveAttribute('aria-pressed', 'true')
  await card.locator('.product-card-link').click()
  await expect(page).toHaveURL(/\/produto\//)
  await expect(page.getByRole('heading', { name: productName, exact: true }).first()).toBeVisible()
})
test('busca, filtro e produto',async({page})=>{await page.goto('/buscar');await page.getByLabel('Buscar no catálogo').fill('headphone');await expect(page.getByText('Headphone Quiet Pro').first()).toBeVisible();await page.getByText('Headphone Quiet Pro').first().click();await expect(page.getByRole('heading',{name:'Headphone Quiet Pro'})).toBeVisible();await expect(page.getByRole('link',{name:/Comprar na/})).toHaveAttribute('href',/^https:\/\//);await expect(page.getByRole('heading',{name:'Outras 2 ofertas'})).toBeVisible()})
test('admin cria registro e respeita leitor',async({page})=>{await page.goto('/admin/produtos');await page.getByRole('button',{name:/Novo produto/}).click();await page.getByLabel('Produto').fill('Produto E2E');await page.getByLabel('Marca').fill('Marca E2E');await page.getByLabel('Categoria').fill('Tecnologia');await page.getByLabel('Score').fill('90');await page.getByRole('button',{name:'Salvar registro'}).click();await expect(page.getByText('Produto E2E')).toBeVisible();await page.locator('.role-switch select').selectOption('viewer');await expect(page.getByText('Modo somente leitura')).toBeVisible()})
