import type { Article, Category, Collection, EventRecord, Job, Offer, Product, Provider } from './types'

export const categories: Category[] = [
  { id:'c1', name:'Tecnologia', slug:'tecnologia', icon:'Cpu', description:'Gadgets úteis para trabalhar, criar e descansar.' },
  { id:'c2', name:'Casa', slug:'casa', icon:'House', description:'Objetos que deixam a rotina mais simples e bonita.' },
  { id:'c3', name:'Áudio', slug:'audio', icon:'Headphones', description:'Som de qualidade para todos os momentos.' },
  { id:'c4', name:'Cozinha', slug:'cozinha', icon:'Coffee', description:'Ferramentas certeiras para preparar e servir.' },
  { id:'c5', name:'Bem-estar', slug:'bem-estar', icon:'Sparkles', description:'Escolhas para cuidar do corpo e da mente.' },
  { id:'c6', name:'Fotografia', slug:'fotografia', icon:'Camera', description:'Equipamentos para registrar boas histórias.' },
]
export const providers: Provider[] = [
  { id:'p1', name:'Amazon', slug:'amazon', rating:4.8, verified:true, color:'#ff9900' },
  { id:'p2', name:'Mercado Livre', slug:'mercado-livre', rating:4.7, verified:true, color:'#ffe600' },
  { id:'p3', name:'Magalu', slug:'magalu', rating:4.6, verified:true, color:'#0086ff' },
  { id:'p4', name:'Loja Oficial', slug:'loja-oficial', rating:4.9, verified:true, color:'#0d2440' },
]
const history = (base:number) => ['Abr','Mai','Jun','Jul','Ago','Set'].map((month,i)=>({month,price:Math.round(base*(1.08-i*.016))}))
export const products: Product[] = [
  { id:'1', name:'Headphone Quiet Pro', slug:'headphone-quiet-pro', brand:'Auralis', category:'audio', description:'Cancelamento de ruído e 40 horas de bateria.', longDescription:'Um headphone confortável para jornadas longas, com som equilibrado, controles intuitivos e isolamento ativo eficiente.', image:'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=900&q=85', images:[], rating:4.8, reviews:1248, score:96, growth:22, tags:['Escolha do editor','Mais acessado'], specs:{Bateria:'40 horas',Conexão:'Bluetooth 5.3',Peso:'254 g',Garantia:'12 meses'}, priceHistory:history(699)},
  { id:'2', name:'Luminária Halo', slug:'luminaria-halo', brand:'Noma', category:'casa', description:'Luz regulável com desenho minimalista.', longDescription:'Iluminação acolhedora para mesa ou cabeceira, com três temperaturas de cor e controle sensível ao toque.', image:'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=900&q=85', images:[], rating:4.7, reviews:539, score:93, growth:31, tags:['Em alta','Design'], specs:{Potência:'12 W',Temperaturas:'3 níveis',Material:'Alumínio',Garantia:'12 meses'}, priceHistory:history(289)},
  { id:'3', name:'Câmera Pocket X', slug:'camera-pocket-x', brand:'Lumina', category:'fotografia', description:'Compacta, rápida e pronta para viajar.', longDescription:'Uma câmera leve para registrar viagens com excelente estabilização e cores naturais, sem complicação.', image:'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=900&q=85', images:[], rating:4.9, reviews:884, score:98, growth:18, tags:['Melhor avaliado'], specs:{Sensor:'24 MP',Vídeo:'4K 60fps',Peso:'410 g',Lente:'24–70 mm'}, priceHistory:history(3299)},
  { id:'4', name:'Moedor Atlas', slug:'moedor-atlas', brand:'Orbe', category:'cozinha', description:'Precisão para cafés mais consistentes.', longDescription:'Moedor manual robusto com ajuste fino e lâminas de aço, feito para quem quer extrair mais de cada grão.', image:'https://images.unsplash.com/photo-1511081692775-05d0f180a065?auto=format&fit=crop&w=900&q=85', images:[], rating:4.6, reviews:317, score:90, growth:14, tags:['Bom custo-benefício'], specs:{Material:'Aço inox',Ajustes:'24 níveis',Capacidade:'30 g',Garantia:'6 meses'}, priceHistory:history(219)},
  { id:'5', name:'Teclado Flow 75', slug:'teclado-flow-75', brand:'Mori', category:'tecnologia', description:'Mecânico, compacto e silencioso.', longDescription:'Teclado de perfil baixo que combina boa digitação, construção sólida e conexão com até três dispositivos.', image:'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=900&q=85', images:[], rating:4.8, reviews:711, score:95, growth:28, tags:['Favorito da comunidade'], specs:{Layout:'75%',Conexão:'Bluetooth e USB-C',Bateria:'80 horas',Switch:'Tátil silencioso'}, priceHistory:history(549)},
  { id:'6', name:'Difusor Brisa', slug:'difusor-brisa', brand:'Sálvia', category:'bem-estar', description:'Aromas suaves e umidade equilibrada.', longDescription:'Difusor ultrassônico silencioso com desligamento automático e acabamento discreto para qualquer ambiente.', image:'https://images.unsplash.com/photo-1602874801006-e26c8c729f4c?auto=format&fit=crop&w=900&q=85', images:[], rating:4.5, reviews:286, score:88, growth:35, tags:['Novidade'], specs:{Capacidade:'300 ml',Autonomia:'10 horas',Ruído:'< 30 dB',Área:'Até 25 m²'}, priceHistory:history(179)},
  { id:'7', name:'Caixa Sonora Mini', slug:'caixa-sonora-mini', brand:'Auralis', category:'audio', description:'Som encorpado em formato portátil.', longDescription:'Caixa compacta resistente à água, com graves surpreendentes e bateria para acompanhar o dia inteiro.', image:'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=900&q=85', images:[], rating:4.6, reviews:968, score:91, growth:19, tags:['Até R$ 300'], specs:{Bateria:'16 horas',Proteção:'IP67',Peso:'380 g',Conexão:'Bluetooth 5.2'}, priceHistory:history(259)},
  { id:'8', name:'Garrafa Térmica Uno', slug:'garrafa-termica-uno', brand:'Noma', category:'casa', description:'Temperatura certa por até 18 horas.', longDescription:'Garrafa de aço com vedação segura, boca larga e acabamento fosco resistente para a rotina.', image:'https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=900&q=85', images:[], rating:4.7, reviews:445, score:92, growth:12, tags:['Mais vendido'], specs:{Capacidade:'750 ml',Material:'Aço inox',Conservação:'18 horas',Garantia:'Vitalícia'}, priceHistory:history(149)},
  { id:'9', name:'Monitor Vision 27', slug:'monitor-vision-27', brand:'Mori', category:'tecnologia', description:'Tela QHD precisa para trabalho e criação.', longDescription:'Monitor de 27 polegadas com ótima definição, base ajustável e conexões modernas para uma mesa mais produtiva.', image:'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=900&q=85', images:[], rating:4.8, reviews:632, score:95, growth:26, tags:['Mais acessado'], specs:{Tela:'27 polegadas QHD',Taxa:'100 Hz',Conexões:'HDMI e USB-C',Garantia:'24 meses'}, priceHistory:history(1699)},
  { id:'10', name:'Mouse Arc Pro', slug:'mouse-arc-pro', brand:'Mori', category:'tecnologia', description:'Precisão silenciosa com ergonomia natural.', longDescription:'Mouse sem fio confortável para uso prolongado, com sensor preciso, rolagem suave e conexão em três dispositivos.', image:'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&w=900&q=85', images:[], rating:4.7, reviews:1194, score:94, growth:33, tags:['Melhor custo-benefício'], specs:{Sensor:'8.000 DPI',Conexão:'Bluetooth e USB',Bateria:'70 dias',Peso:'108 g'}, priceHistory:history(389)},
  { id:'11', name:'Hub Dock 8 em 1', slug:'hub-dock-8-em-1', brand:'Nexo', category:'tecnologia', description:'Todas as conexões em uma única porta.', longDescription:'Hub compacto em alumínio com HDMI, leitor de cartões, rede e carregamento rápido para notebooks USB-C.', image:'https://images.unsplash.com/photo-1625842268584-8f3296236761?auto=format&fit=crop&w=900&q=85', images:[], rating:4.6, reviews:487, score:90, growth:21, tags:['Essencial para a mesa'], specs:{Portas:'8',Vídeo:'4K 60 Hz',Energia:'100 W',Material:'Alumínio'}, priceHistory:history(279)},
  { id:'12', name:'Aspirador Vertical Move', slug:'aspirador-vertical-move', brand:'Orbe', category:'casa', description:'Limpeza rápida sem fio e sem esforço.', longDescription:'Aspirador leve com boa autonomia, filtro lavável e acessórios para pisos, estofados e cantos.', image:'https://images.unsplash.com/photo-1558317374-067fb5f30001?auto=format&fit=crop&w=900&q=85', images:[], rating:4.7, reviews:908, score:93, growth:29, tags:['Casa prática'], specs:{Autonomia:'45 minutos',Potência:'180 W',Filtro:'HEPA lavável',Peso:'2,3 kg'}, priceHistory:history(899)},
  { id:'13', name:'Cadeira Ergo One', slug:'cadeira-ergo-one', brand:'Noma', category:'casa', description:'Apoio inteligente para longas jornadas.', longDescription:'Cadeira ergonômica com ajustes essenciais, tela respirável e suporte lombar para trabalhar com mais conforto.', image:'https://images.unsplash.com/photo-1580480055273-228ff5388ef8?auto=format&fit=crop&w=900&q=85', images:[], rating:4.8, reviews:731, score:96, growth:24, tags:['Escolha da comunidade'], specs:{Ajustes:'6 níveis',Carga:'Até 130 kg',Material:'Tela mesh',Garantia:'36 meses'}, priceHistory:history(1299)},
  { id:'14', name:'Earbuds Pulse Air', slug:'earbuds-pulse-air', brand:'Auralis', category:'audio', description:'Som compacto com cancelamento de ruído.', longDescription:'Fones leves com encaixe confortável, chamadas nítidas e estojo de carregamento para acompanhar a semana.', image:'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=900&q=85', images:[], rating:4.7, reviews:1532, score:95, growth:38, tags:['Em alta'], specs:{Bateria:'32 horas',Proteção:'IPX5',Conexão:'Bluetooth 5.3',Microfones:'6'}, priceHistory:history(499)},
  { id:'15', name:'Soundbar Frame', slug:'soundbar-frame', brand:'Auralis', category:'audio', description:'Cinema em casa sem ocupar espaço.', longDescription:'Soundbar fina com graves definidos, vozes claras e conexão simples para filmes, séries e música.', image:'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=900&q=85', images:[], rating:4.8, reviews:624, score:94, growth:27, tags:['Sala completa'], specs:{Potência:'240 W',Canais:'3.1',Conexão:'HDMI eARC',Modos:'4'}, priceHistory:history(1199)},
  { id:'16', name:'Air Fryer Crisp 5L', slug:'air-fryer-crisp-5l', brand:'Orbe', category:'cozinha', description:'Mais espaço e crocância no dia a dia.', longDescription:'Fritadeira ampla com controle preciso de temperatura, cesto fácil de limpar e programas para receitas rápidas.', image:'/products/air-fryer-crisp.png', images:[], rating:4.8, reviews:2148, score:97, growth:41, tags:['Mais vendido'], specs:{Capacidade:'5 litros',Potência:'1.700 W',Temperatura:'80–200 °C',Programas:'8'}, priceHistory:history(549)},
  { id:'17', name:'Cafeteira Moka Touch', slug:'cafeteira-moka-touch', brand:'Orbe', category:'cozinha', description:'Café consistente com um toque.', longDescription:'Cafeteira compacta com extração programável, vaporizador e controles simples para começar bem o dia.', image:'https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?auto=format&fit=crop&w=900&q=85', images:[], rating:4.7, reviews:876, score:93, growth:23, tags:['Café em casa'], specs:{Pressão:'15 bar',Reservatório:'1,2 litro',Potência:'1.350 W',Garantia:'12 meses'}, priceHistory:history(799)},
  { id:'18', name:'Panela Ferro Duo', slug:'panela-ferro-duo', brand:'Atlas', category:'cozinha', description:'Calor uniforme para receitas memoráveis.', longDescription:'Panela de ferro esmaltado que conserva o calor, vai do fogão ao forno e serve com elegância.', image:'https://images.unsplash.com/photo-1584990347449-a4204e0ab8da?auto=format&fit=crop&w=900&q=85', images:[], rating:4.9, reviews:352, score:96, growth:17, tags:['Escolha do editor'], specs:{Capacidade:'4,5 litros',Material:'Ferro fundido',Forno:'Até 260 °C',Garantia:'10 anos'}, priceHistory:history(649)},
  { id:'19', name:'Massageador Pocket', slug:'massageador-pocket', brand:'Sálvia', category:'bem-estar', description:'Alívio muscular que cabe na bolsa.', longDescription:'Massageador compacto com intensidades ajustáveis e operação silenciosa para recuperação depois do treino.', image:'https://images.unsplash.com/photo-1600334089648-b0d9d3028eb2?auto=format&fit=crop&w=900&q=85', images:[], rating:4.6, reviews:611, score:89, growth:36, tags:['Recuperação'], specs:{Intensidades:'4',Bateria:'5 horas',Peso:'480 g',Ponteiras:'4'}, priceHistory:history(329)},
  { id:'20', name:'Balança Smart Balance', slug:'balanca-smart-balance', brand:'Sálvia', category:'bem-estar', description:'Acompanhe sua evolução com simplicidade.', longDescription:'Balança conectada com leitura corporal, perfis familiares e histórico organizado no aplicativo.', image:'https://images.unsplash.com/photo-1576678927484-cc907957088c?auto=format&fit=crop&w=900&q=85', images:[], rating:4.7, reviews:784, score:91, growth:20, tags:['Rotina saudável'], specs:{Métricas:'13',Perfis:'Ilimitados',Conexão:'Bluetooth',Carga:'Até 180 kg'}, priceHistory:history(239)},
  { id:'21', name:'Tapete Yoga Ground', slug:'tapete-yoga-ground', brand:'Sálvia', category:'bem-estar', description:'Estabilidade e conforto em cada prática.', longDescription:'Tapete aderente e confortável, produzido com material durável e fácil de limpar para exercícios em casa.', image:'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?auto=format&fit=crop&w=900&q=85', images:[], rating:4.8, reviews:429, score:92, growth:16, tags:['Bem avaliado'], specs:{Espessura:'6 mm',Comprimento:'183 cm',Material:'Borracha natural',Peso:'2,1 kg'}, priceHistory:history(219)},
  { id:'22', name:'Tripé Travel Carbon', slug:'tripe-travel-carbon', brand:'Lumina', category:'fotografia', description:'Estabilidade profissional sem peso extra.', longDescription:'Tripé compacto em fibra de carbono, com montagem rápida e cabeça fluida para foto e vídeo em viagens.', image:'https://images.unsplash.com/photo-1452780212940-6f5c0d14d848?auto=format&fit=crop&w=900&q=85', images:[], rating:4.8, reviews:288, score:94, growth:19, tags:['Para viajar'], specs:{Altura:'160 cm',Carga:'8 kg',Peso:'1,2 kg',Material:'Fibra de carbono'}, priceHistory:history(899)},
  { id:'23', name:'Luz LED Pocket', slug:'luz-led-pocket', brand:'Lumina', category:'fotografia', description:'Luz suave para fotos e vídeos melhores.', longDescription:'Painel LED de bolso com temperatura ajustável, bateria interna e montagem universal para criadores.', image:'https://images.unsplash.com/photo-1535223289827-42f1e9919769?auto=format&fit=crop&w=900&q=85', images:[], rating:4.6, reviews:516, score:90, growth:30, tags:['Para criadores'], specs:{Temperatura:'2.500–8.500 K',Bateria:'140 minutos',LEDs:'96',Peso:'180 g'}, priceHistory:history(299)},
  { id:'24', name:'Mochila Camera Trek', slug:'mochila-camera-trek', brand:'Lumina', category:'fotografia', description:'Proteção modular para todo o seu kit.', longDescription:'Mochila resistente à água com divisórias ajustáveis, abertura segura e espaço para notebook e acessórios.', image:'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=900&q=85', images:[], rating:4.7, reviews:391, score:92, growth:15, tags:['Kit protegido'], specs:{Volume:'24 litros',Notebook:'Até 16 polegadas',Proteção:'Resistente à água',Peso:'1,1 kg'}, priceHistory:history(479)},
]
products.forEach((product) => {
  const separator = product.image.includes('?') ? '&' : '?'
  product.images = [
    product.image,
    `${product.image}${separator}sat=-8&bri=5`,
    `${product.image}${separator}crop=entropy&sat=6&bri=-4`,
  ]
})
const providerUrl = (providerId: string, product: Product) => {
  const query = encodeURIComponent(`${product.brand} ${product.name}`)
  if (providerId === 'p1') return `https://www.amazon.com.br/s?k=${query}`
  if (providerId === 'p2') return `https://lista.mercadolivre.com.br/${encodeURIComponent(product.name.replaceAll(' ', '-'))}`
  if (providerId === 'p3') return `https://www.magazineluiza.com.br/busca/${encodeURIComponent(product.name)}/`
  return `https://www.google.com/search?tbm=shop&q=${query}`
}
export const offers: Offer[] = products.flatMap((product,index)=>[
  {id:`o${index}a`,productId:product.id,providerId:'p1',price:product.priceHistory.at(-1)!.price,previousPrice:Math.round(product.priceHistory[0].price*1.05),shipping:0,installment:'10x sem juros',stock:'disponível',url:providerUrl('p1',product),updatedAt:'há 8 min'},
  {id:`o${index}b`,productId:product.id,providerId:'p2',price:Math.round(product.priceHistory.at(-1)!.price*1.04),shipping:19.9,installment:'12x com juros',stock:index%3===0?'últimas unidades':'disponível',url:providerUrl('p2',product),updatedAt:'há 22 min'},
  {id:`o${index}c`,productId:product.id,providerId:index%2?'p3':'p4',price:Math.round(product.priceHistory.at(-1)!.price*.98),shipping:29.9,installment:'8x sem juros',stock:'disponível',url:providerUrl(index%2?'p3':'p4',product),updatedAt:'há 1 h'},
])
export const collections: Collection[] = [
  {id:'cl1',title:'Mesa bem resolvida',slug:'mesa-bem-resolvida',description:'Peças para trabalhar com mais foco e menos ruído.',productIds:['1','5','9','10','11','13'],tone:'Foco'},
  {id:'cl2',title:'Casa prática',slug:'casa-pratica',description:'Escolhas que economizam tempo na rotina e facilitam o cuidado da casa.',productIds:['8','12','16','17','18'],tone:'Rotina leve'},
  {id:'cl3',title:'Até R$ 300',slug:'ate-300',description:'Boas escolhas que cabem no orçamento.',productIds:['4','6','7','8','11','20','21','23'],tone:'Preço justo'},
]
export const articles: Article[] = [
  {id:'a1',title:'Como escolher um headphone sem cair no hype',slug:'como-escolher-headphone',excerpt:'Cinco critérios que importam mais do que a ficha técnica.',category:'Guia de compra',readTime:'6 min',image:'https://images.unsplash.com/photo-1484704849700-f032a568e944?auto=format&fit=crop&w=1200&q=85',content:['Conforto vem antes de qualquer codec. Um bom headphone precisa desaparecer na cabeça depois dos primeiros minutos.','Compare autonomia real, peso e facilidade de troca entre dispositivos. Cancelamento de ruído forte não compensa um arco desconfortável.','Por fim, consulte o histórico de preço e compare a reputação das lojas antes de decidir.']},
  {id:'a2',title:'Uma mesa melhor começa pela luz',slug:'mesa-melhor-luz',excerpt:'Temperatura, posição e intensidade para reduzir o cansaço.',category:'Casa e rotina',readTime:'4 min',image:'https://images.unsplash.com/photo-1494438639946-1ebd1d20bf85?auto=format&fit=crop&w=1200&q=85',content:['A luz lateral reduz reflexos e cria profundidade sem disputar atenção com a tela.','Durante o dia, prefira tons neutros. À noite, luzes quentes ajudam a sinalizar que o expediente terminou.']},
  {id:'a3',title:'O kit essencial para fotografar viagens',slug:'kit-fotografia-viagem',excerpt:'Menos equipamento, mais histórias para registrar.',category:'Seleção',readTime:'8 min',image:'https://images.unsplash.com/photo-1452780212940-6f5c0d14d848?auto=format&fit=crop&w=1200&q=85',content:['Uma lente versátil, bateria extra e alça confortável resolvem a maioria dos cenários.','Escolha uma bolsa discreta e reserve espaço para deixar a câmera acessível.']},
]
export const jobs: Job[] = [
 {id:'j1',name:'Sincronização de ofertas',provider:'Amazon',status:'Concluído',progress:100,lastRun:'Hoje, 09:42'},
 {id:'j2',name:'Atualização de estoque',provider:'Mercado Livre',status:'Em execução',progress:68,lastRun:'Agora'},
 {id:'j3',name:'Normalização de catálogo',provider:'Magalu',status:'Com alerta',progress:84,lastRun:'Hoje, 08:10'},
]
export const auditEvents: EventRecord[] = [
 {id:'e1',type:'Produto atualizado',subject:'Headphone Quiet Pro',actor:'Marina Costa',at:'Hoje, 10:32'},
 {id:'e2',type:'Campanha publicada',subject:'Semana do essencial',actor:'Rafael Lima',at:'Hoje, 09:14'},
 {id:'e3',type:'Provider sincronizado',subject:'Amazon',actor:'Sistema',at:'Hoje, 08:57'},
 {id:'e4',type:'Regra alterada',subject:'Ranking — custo-benefício',actor:'Marina Costa',at:'Ontem, 18:21'},
]
export const adminModules = [
 ['Catálogo',['Produtos','Ofertas','Providers','Categorias','Marcas','Tags','Coleções','Imports e jobs']],
 ['Experiência',['Home Builder','Recommendation Slots','Ranking','Segmentos','Campanhas','Experimentos A/B']],
 ['Conteúdo',['CMS','Páginas','SEO']],
 ['Insights',['Analytics','Funil','Eventos']],
 ['Governança',['Usuários e RBAC','LGPD','Audit Log','Logs']],
 ['Sistema',['Integrações','Tracking','AI','Segurança','Tema']],
] as const
export const formatPrice=(value:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(value)
export const getProduct=(slug:string)=>products.find(p=>p.slug===slug)
export const getOffers=(id:string)=>offers.filter(o=>o.productId===id).sort((a,b)=>(a.price+a.shipping)-(b.price+b.shipping))
export const getBestOffer=(id:string)=>getOffers(id).find(offer=>offer.stock!=='indisponível')
export const getProvider=(id:string)=>providers.find(p=>p.id===id)!
