'use client'

import { useMemo, useState } from 'react'
import { Beaker, Check, ChevronDown, GripVertical, Plus, Save, SlidersHorizontal, Trash2 } from 'lucide-react'
import { generateRecommendations, assignExperiment, type CandidateSource, type ScoringWeights } from '@/lib/recommendation/engine'
import { products } from '@/lib/mock-data'
import { platformServices } from '@/lib/platform'

type Props = { slug: string; disabled: boolean; notify: (message: string) => void }
type Rule = { id: string; field: string; operator: string; value: string }
const sourceLabels: Record<CandidateSource, string> = { trending:'Em alta',category:'Categoria',similar:'Similares',history:'Histórico',favorites:'Favoritos',co_visit:'Co-visita',co_click:'Co-clique',editorial:'Editorial',price_drop:'Queda de preço',high_rating:'Bem avaliados',new_products:'Novidades' }
const studioSlugs = new Set(['home-builder','recommendation-slots','ranking','segmentos','campanhas','experimentos','tema','colecoes'])
export const hasExperienceStudio = (slug: string) => studioSlugs.has(slug)

function persist(slug: string, value: unknown, notify: Props['notify']) {
  localStorage.setItem(`garimpo:studio:${slug}`, JSON.stringify({ ...value as object, version: Date.now(), publishedAt: new Date().toISOString() }))
  platformServices.tracker.track({ name: 'studio_version_published', resource: slug, actor: 'Marina' })
  notify('Nova versão mock publicada e adicionada à trilha de auditoria.')
}

export function ExperienceStudio(props: Props) {
  if (props.slug === 'ranking') return <RankingStudio {...props}/>
  if (props.slug === 'recommendation-slots') return <SlotStudio {...props}/>
  if (props.slug === 'segmentos') return <SegmentStudio {...props}/>
  if (props.slug === 'home-builder') return <HomeStudio {...props}/>
  if (props.slug === 'tema') return <ThemeStudio {...props}/>
  if (props.slug === 'experimentos') return <ExperimentStudio {...props}/>
  if (props.slug === 'campanhas') return <CampaignStudio {...props}/>
  return <CollectionStudio {...props}/>
}

function StudioFrame({ eyebrow, title, children, aside }: { eyebrow: string; title: string; children: React.ReactNode; aside: React.ReactNode }) {
  return <section className="studio"><div className="studio-main"><div className="studio-heading"><span className="kicker">{eyebrow}</span><h2>{title}</h2></div>{children}</div><aside className="studio-aside">{aside}</aside></section>
}

function RankingStudio({ disabled, notify }: Props) {
  const [weights, setWeights] = useState<ScoringWeights>({ relevance:18, affinity:15, engagement:14, quality:16, commercial:8, price:12, freshness:8, similarity:9 })
  const [exploration, setExploration] = useState(12); const [sample, setSample] = useState(80); const [seed, setSeed] = useState('simulacao-admin')
  const snapshot = useMemo(() => generateRecommendations({ seed, limit: 6, explorationRate: exploration / 100, weights }), [weights, exploration, seed])
  const labels: Record<keyof ScoringWeights,string> = { relevance:'Relevância',affinity:'Afinidade',engagement:'Engajamento',quality:'Qualidade',commercial:'Valor comercial',price:'Preço',freshness:'Frescor',similarity:'Similaridade' }
  return <StudioFrame eyebrow="SCORING LAB" title="Perfil de ranking sustentável" aside={<><h3>Controles do modelo</h3><label>Exploration <strong>{exploration}%</strong><input type="range" min="0" max="40" value={exploration} disabled={disabled} onChange={(e)=>setExploration(+e.target.value)}/></label><label>Amostra mínima<input className="input" type="number" value={sample} disabled={disabled} onChange={(e)=>setSample(+e.target.value)}/></label><label>Seed de simulação<input className="input" value={seed} onChange={(e)=>setSeed(e.target.value)}/></label><button className="btn primary full" disabled={disabled} onClick={()=>persist('ranking',{weights,exploration,sample},notify)}><Save/> Publicar perfil</button></>}><div className="weight-grid">{Object.entries(weights).map(([key,value])=><label className="weight-control" key={key}><span>{labels[key as keyof ScoringWeights]}<strong>{value}</strong></span><input type="range" min="0" max="40" value={value} disabled={disabled} onChange={(e)=>setWeights((current)=>({...current,[key]:+e.target.value}))}/></label>)}</div><div className="simulation-list"><div className="simulation-head"><h3>Re-ranking simulado</h3><span>{snapshot.algorithmVersion} · {snapshot.diagnostics.explorationCount} exploração</span></div>{snapshot.recommendations.map((item,index)=><article key={item.product.id}><b>{index+1}</b><img src={item.product.image} alt=""/><span><strong>{item.product.name}</strong><small>{item.reason} · {item.sources.slice(0,3).map((source)=>sourceLabels[source]).join(', ')}</small></span><em>{(item.score*100).toFixed(1)}</em></article>)}</div></StudioFrame>
}

function SlotStudio({ disabled, notify }: Props) {
  const allSources = Object.keys(sourceLabels) as CandidateSource[]; const [slot,setSlot]=useState('home_for_you'); const [sources,setSources]=useState<CandidateSource[]>(['history','favorites','category','trending']); const [limit,setLimit]=useState(8); const [ttl,setTtl]=useState(900); const [fallback,setFallback]=useState('editorial')
  function toggle(source:CandidateSource){setSources((current)=>current.includes(source)?current.filter((item)=>item!==source):[...current,source])}
  return <StudioFrame eyebrow="SLOT ORCHESTRATOR" title="Estratégia por superfície" aside={<><h3>Contrato do slot</h3><label>Slot<select className="select" value={slot} onChange={(e)=>setSlot(e.target.value)}><option>home_for_you</option><option>home_trending</option><option>product_similar</option><option>category_personalized</option></select></label><label>Limite<input className="input" type="number" min="1" max="20" value={limit} onChange={(e)=>setLimit(+e.target.value)}/></label><label>Cache TTL<input className="input" type="number" value={ttl} onChange={(e)=>setTtl(+e.target.value)}/></label><label>Fallback<select className="select" value={fallback} onChange={(e)=>setFallback(e.target.value)}><option value="editorial">Curadoria editorial</option><option value="trending">Em alta</option><option value="high_rating">Bem avaliados</option></select></label><button className="btn primary full" disabled={disabled||!sources.length} onClick={()=>persist('recommendation-slots',{slot,sources,limit,ttl,fallback},notify)}><Save/> Salvar slot</button></>}><div className="source-grid">{allSources.map((source)=><button key={source} disabled={disabled} aria-pressed={sources.includes(source)} className={sources.includes(source)?'source-chip active':'source-chip'} onClick={()=>toggle(source)}><Check/>{sourceLabels[source]}</button>)}</div><div className="pipeline-map"><div><b>1</b><span>Candidate generation<small>{sources.length} fontes ativas</small></span></div><ChevronDown/><div><b>2</b><span>Scoring<small>Perfil sustentável v2.1</small></span></div><ChevronDown/><div><b>3</b><span>Re-ranking<small>Diversidade e regras</small></span></div></div></StudioFrame>
}

function SegmentStudio({ disabled, notify }: Props) {
  const [logic,setLogic]=useState<'AND'|'OR'>('AND'); const [rules,setRules]=useState<Rule[]>([{id:'r1',field:'category_views_7d',operator:'>=',value:'3'},{id:'r2',field:'favorite_category',operator:'=',value:'café'},{id:'r3',field:'affiliate_click_24h',operator:'=',value:'0'}])
  const reach=Math.max(340,Math.round(48200/(rules.length*1.7)*(logic==='OR'?1.8:1)))
  return <StudioFrame eyebrow="AUDIENCE LOGIC" title="Segmento comportamental" aside={<><h3>Estimativa</h3><div className="reach-number"><strong>{reach.toLocaleString('pt-BR')}</strong><span>sessões elegíveis</span></div><p>Somente sinais não sensíveis, com frequência, recência e intensidade.</p><button className="btn primary full" disabled={disabled||!rules.length} onClick={()=>persist('segmentos',{logic,rules,reach},notify)}><Save/> Publicar segmento</button></>}><div className="logic-switch"><button className={logic==='AND'?'active':''} onClick={()=>setLogic('AND')}>E · todas</button><button className={logic==='OR'?'active':''} onClick={()=>setLogic('OR')}>OU · qualquer</button></div><div className="rule-list">{rules.map((rule,index)=><div className="rule-row" key={rule.id}><b>{index+1}</b><select value={rule.field} disabled={disabled} onChange={(e)=>setRules((current)=>current.map((item)=>item.id===rule.id?{...item,field:e.target.value}:item))}><option value="category_views_7d">Visualizações de categoria · 7d</option><option value="favorite_category">Categoria favoritada</option><option value="affiliate_click_24h">Clique afiliado · 24h</option><option value="device">Dispositivo</option><option value="source">Origem</option></select><select value={rule.operator} disabled={disabled} onChange={(e)=>setRules((current)=>current.map((item)=>item.id===rule.id?{...item,operator:e.target.value}:item))}><option>&gt;=</option><option>=</option><option>!=</option><option>contém</option></select><input value={rule.value} disabled={disabled} onChange={(e)=>setRules((current)=>current.map((item)=>item.id===rule.id?{...item,value:e.target.value}:item))}/><button aria-label="Remover condição" disabled={disabled} onClick={()=>setRules((current)=>current.filter((item)=>item.id!==rule.id))}><Trash2/></button></div>)}</div><button className="btn secondary" disabled={disabled} onClick={()=>setRules((current)=>[...current,{id:crypto.randomUUID(),field:'device',operator:'=',value:'mobile'}])}><Plus/> Adicionar condição</button></StudioFrame>
}

function HomeStudio({ disabled, notify }: Props) {
  const [blocks,setBlocks]=useState([{id:'hero',name:'Hero editorial',audience:'Todos',enabled:true},{id:'foryou',name:'Para você',audience:'Personalizado',enabled:true},{id:'trending',name:'Radar em alta',audience:'Todos',enabled:true},{id:'guides',name:'Guias de compra',audience:'Todos',enabled:true}]); const [selected,setSelected]=useState(0)
  function move(index:number,direction:number){const target=index+direction;if(target<0||target>=blocks.length)return;setBlocks((current)=>{const next=[...current];[next[index],next[target]]=[next[target],next[index]];return next});setSelected(target)}
  const current=blocks[selected]
  return <StudioFrame eyebrow="COMPOSITION BUILDER" title="Homepage por blocos" aside={<><h3>Bloco selecionado</h3>{current&&<><label>Nome<input className="input" value={current.name} disabled={disabled} onChange={(e)=>setBlocks((items)=>items.map((item,index)=>index===selected?{...item,name:e.target.value}:item))}/></label><label>Audiência<select className="select" value={current.audience} disabled={disabled} onChange={(e)=>setBlocks((items)=>items.map((item,index)=>index===selected?{...item,audience:e.target.value}:item))}><option>Todos</option><option>Personalizado</option><option>Tecnologia</option><option>Cozinha</option></select></label></>}<button className="btn primary full" disabled={disabled} onClick={()=>persist('home-builder',{blocks},notify)}><Save/> Publicar versão</button></>}><div className="composition-list">{blocks.map((block,index)=><article className={selected===index?'active':''} key={block.id} onClick={()=>setSelected(index)}><GripVertical/><b>{index+1}</b><span><strong>{block.name}</strong><small>{block.audience}</small></span><div><button disabled={disabled||index===0} aria-label="Mover para cima" onClick={(e)=>{e.stopPropagation();move(index,-1)}}>↑</button><button disabled={disabled||index===blocks.length-1} aria-label="Mover para baixo" onClick={(e)=>{e.stopPropagation();move(index,1)}}>↓</button></div></article>)}</div><div className="home-mini-preview">{blocks.filter((block)=>block.enabled).map((block,index)=><div className={index===0?'hero-mini':''} key={block.id}><small>{block.audience}</small><strong>{block.name}</strong></div>)}</div></StudioFrame>
}

function ThemeStudio({ disabled, notify }: Props) {
  const [theme,setTheme]=useState({primary:'#0d9488',background:'#0b1220',foreground:'#f4f7fb',radius:12,density:'Confortável'})
  return <StudioFrame eyebrow="TOKEN EDITOR" title="Tema e densidade" aside={<><h3>Tokens</h3><label>Primary<input type="color" value={theme.primary} disabled={disabled} onChange={(e)=>setTheme({...theme,primary:e.target.value})}/></label><label>Background<input type="color" value={theme.background} disabled={disabled} onChange={(e)=>setTheme({...theme,background:e.target.value})}/></label><label>Foreground<input type="color" value={theme.foreground} disabled={disabled} onChange={(e)=>setTheme({...theme,foreground:e.target.value})}/></label><label>Raio · {theme.radius}px<input type="range" min="0" max="24" value={theme.radius} disabled={disabled} onChange={(e)=>setTheme({...theme,radius:+e.target.value})}/></label><button className="btn primary full" disabled={disabled} onClick={()=>persist('tema',{theme},notify)}><Save/> Publicar tema</button></>}><div className="theme-preview" style={{background:theme.background,color:theme.foreground,borderRadius:theme.radius}}><span style={{color:theme.primary}}>GARIMPO · PREVIEW</span><h3>Escolhas boas, sem ruído.</h3><p>Uma superfície de demonstração dos tokens sem alterar o tema ativo antes da publicação.</p><button style={{background:theme.primary,color:theme.background,borderRadius:Math.max(4,theme.radius-4)}}>Explorar seleção</button><div><i/><i/><i/></div></div></StudioFrame>
}

function ExperimentStudio({ disabled, notify }: Props) {
  const [name,setName]=useState('Ordem da vitrine hero'); const [allocation,setAllocation]=useState(50); const [subject,setSubject]=useState('session-demo'); const assignment=assignExperiment('hero-order-v2',subject,['controle','variante-b'])
  return <StudioFrame eyebrow="EXPERIMENT LAB" title="Teste com assignment sticky" aside={<><h3>Configuração</h3><label>Hipótese<input className="input" value={name} onChange={(e)=>setName(e.target.value)}/></label><label>Tráfego · {allocation}%<input type="range" value={allocation} disabled={disabled} onChange={(e)=>setAllocation(+e.target.value)}/></label><label>Métrica<select className="select"><option>commission_per_session</option><option>conversion_rate</option><option>favorite_rate</option></select></label><button className="btn primary full" disabled={disabled} onClick={()=>persist('experimentos',{name,allocation},notify)}><Beaker/> Iniciar experimento</button></>}><div className="variant-grid"><article><span>CONTROLE</span><h3>Ordem editorial</h3><p>Curadoria atual sem alterações.</p></article><article><span>VARIANTE B</span><h3>Ordem personalizada</h3><p>Ranking por afinidade e frescor.</p></article></div><div className="assignment-box"><label>Subject para conferir estabilidade<input className="input" value={subject} onChange={(e)=>setSubject(e.target.value)}/></label><p>Assignment: <strong>{assignment.variant}</strong> · {assignment.assignmentId}</p></div></StudioFrame>
}

function CampaignStudio({ disabled, notify }: Props) {
  const [campaign,setCampaign]=useState({name:'Semana do essencial',placement:'Hero da home',segment:'Todos',start:'2026-09-05',end:'2026-09-12',headline:'Menos ruído. Melhores escolhas.',cta:'Explorar seleção'})
  return <StudioFrame eyebrow="ON-SITE CAMPAIGN" title="Campanha versionada e agendada" aside={<><h3>Entrega</h3>{(['name','placement','segment','start','end'] as const).map((key)=><label key={key}>{({name:'Nome',placement:'Posição',segment:'Segmento',start:'Início',end:'Fim'})[key]}<input className="input" type={key==='start'||key==='end'?'date':'text'} value={campaign[key]} disabled={disabled} onChange={(e)=>setCampaign({...campaign,[key]:e.target.value})}/></label>)}<button className="btn primary full" disabled={disabled} onClick={()=>persist('campanhas',{campaign},notify)}><Save/> Agendar campanha</button></>}><div className="campaign-preview"><span>CONTEÚDO PERSONALIZADO</span><h3>{campaign.headline}</h3><input value={campaign.headline} disabled={disabled} aria-label="Headline" onChange={(e)=>setCampaign({...campaign,headline:e.target.value})}/><button>{campaign.cta}</button><small>{campaign.segment} · {campaign.placement}</small></div></StudioFrame>
}

function CollectionStudio({ disabled, notify }: Props) {
  const [title,setTitle]=useState('Mesa bem resolvida'); const [selected,setSelected]=useState(['1','2','5'])
  return <StudioFrame eyebrow="EDITORIAL COLLECTION" title="Curadoria de produtos" aside={<><h3>Publicação</h3><label>Título<input className="input" value={title} disabled={disabled} onChange={(e)=>setTitle(e.target.value)}/></label><p>{selected.length} produtos selecionados e ordenados.</p><button className="btn primary full" disabled={disabled||!selected.length} onClick={()=>persist('colecoes',{title,selected},notify)}><Save/> Publicar coleção</button></>}><div className="product-picker">{products.map((product)=><button key={product.id} disabled={disabled} aria-pressed={selected.includes(product.id)} className={selected.includes(product.id)?'active':''} onClick={()=>setSelected((current)=>current.includes(product.id)?current.filter((id)=>id!==product.id):[...current,product.id])}><img src={product.image} alt=""/><span><strong>{product.name}</strong><small>{product.category} · score {product.score}</small></span><Check/></button>)}</div></StudioFrame>
}
