'use client'

import useSWR from 'swr'
import { Activity, AlertTriangle, CheckCircle2, RefreshCw, Server, ShieldCheck } from 'lucide-react'

type Health={status:string;uptimeSeconds:number;runtime:{heapUsedMb:number;node:string};checks:Record<string,{status:string;latencyMs?:number;depth?:number;heartbeat?:string;healthy?:number;degraded?:number}>;circuits:Array<{name:string;state:string}>}
type Log={id:string;timestamp:string;level:string;service:string;message:string;durationMs?:number;status?:string;retryCount?:number}
type Response={data:{health:Health;logs:Log[];circuits:Array<{name:string;state:string}>}}
const fetcher=(url:string)=>fetch(url).then(async(response)=>{if(!response.ok)throw new Error('Falha no status operacional');return response.json() as Promise<Response>})
export const hasOperationsStudio=(slug:string)=>['logs','integracoes','seguranca'].includes(slug)
export function OperationsStudio(){const{data,error,isLoading,mutate}=useSWR<Response>('/api/v1/operations',fetcher,{refreshInterval:15000});const health=data?.data.health
  if(isLoading)return <div className="panel operation-loading"><RefreshCw className="spin"/> Consultando serviços...</div>
  if(error||!health)return <div className="panel access-denied"><AlertTriangle/><h2>Status indisponível</h2><button className="btn secondary" onClick={()=>mutate()}>Tentar novamente</button></div>
  return <section className="operations-studio"><div className="ops-summary"><div><span className="health-dot"/><strong>Plataforma saudável</strong><small>Atualização automática a cada 15 segundos</small></div><button className="btn secondary" onClick={()=>mutate()}><RefreshCw/> Atualizar</button></div><div className="ops-grid"><article><Activity/><span><small>Uptime</small><strong>{health.uptimeSeconds}s</strong></span></article><article><Server/><span><small>Heap utilizado</small><strong>{health.runtime.heapUsedMb} MB</strong></span></article><article><ShieldCheck/><span><small>Circuit breakers</small><strong>{health.circuits.filter((item)=>item.state==='open').length} abertos</strong></span></article></div><div className="admin-grid"><div className="panel"><h2>Health checks</h2>{Object.entries(health.checks).map(([name,check])=><div className="health-row" key={name}><CheckCircle2/><span><strong>{name}</strong><small>{check.latencyMs?`${check.latencyMs} ms`:check.heartbeat??(check.depth!==undefined?`${check.depth} itens na fila`:`${check.healthy??0} saudáveis · ${check.degraded??0} degradados`)}</small></span><em>{check.status}</em></div>)}</div><div className="panel"><h2>Logs estruturados</h2>{data.data.logs.map((entry)=><div className="log-row" key={entry.id}><span className={`log-level ${entry.level}`}>{entry.level}</span><div><strong>{entry.service}</strong><p>{entry.message}</p><small>{entry.durationMs??0} ms · retry {entry.retryCount??0} · {new Date(entry.timestamp).toLocaleTimeString('pt-BR')}</small></div></div>)}</div></div><div className="ops-contract"><code>request_id</code><code>trace_id</code><code>job_id</code><code>provider</code><code>duration</code><span>Campos sensíveis são removidos antes do log.</span></div></section>}
